### ISSUE TITLE
init BSpline

### ISSUE THREAD

**Issue by ErikLambr** [meco-group/cpp_splines#13]
`test_argument_strips.py` faalt op `BS2 = Basis.BSplineBasis([0.0 ,1.0 ],3,4)` 
met error mesage 
`Wrong number or type of arguments for overloaded function 'new_BSplineBasis'`
Maar hoe kan ik zie hoeveel python er 'ziet'?

**Comment by jgillis** [comment]
Het moet `const std::vector<double>&` als argument zijn, niet `std::vector<double>&`.
Hoeveel python er ziet is geen eenduidig concept in SWIG, dus helaas is er niet echt een betere error message mogelijk. (CasADi heeft er wel een beter door een `masssive hack`.)

**Comment by jgillis** [comment]
Misschien even verklaren waarom const ref zo belangrijk is in de SWIG interface..
Als het niet const-ref was, zou je een Python object moeten construeren dat zichzelf update wanneer er iets met de std::vector gebeurt in C++. Omgekeerd zou de std::vector in C++ zichzelf moeten aanpassen wanneer je de lijst in Python wijzigt.
Dit zou erg moeilijk te implementeren zijn.
Met const ref kan de SWIG typemap gewoon eenmalig de conversie van lijst naar std::vector doen en daarmee is de kous af.
