### ISSUE TITLE
Job 226.1  Travis failing on tests, localy works

### ISSUE THREAD

**Issue by ErikLambr** [meco-group/cpp_splines#30]
10: ======================================================================
10: FAIL: test_getDimenstion1 (__main__.Test_Basis_SubBasis)
10: ----------------------------------------------------------------------
10: Traceback (most recent call last):
10:   File "/home/travis/build/meco-group/cpp_splines/tests/test_basis_Basis.py", line 32, in test_getDimenstion1
10:     self.assertEqual(b.getDimension(), 3)
10: AssertionError: 2 != 3
10: 
10: ----------------------------------------------------------------------
10: Ran 8 tests in 0.003s
10: 
10: FAILED (failures=1)
5/8 Test #10: python_test_basis_Basis ................***Failed    0.68 sec

**Comment by jgillis** [comment]
Dissapeared after merging in develop again
