### ISSUE TITLE
Problems with indexing [Matlab+Windows]

### ISSUE THREAD

**Issue by gpipelee** [meco-group/cpp_splines#37]
```
m = SubMonomialBasis(degree);
sbv = SubBasisVector();
sbv.append(m);
sbv.append(m);
b = Basis.Basis(sbv);

b.getSubBasis(i) 
```
- MATLAB crash (Matlab System Error) unless `i=0` or `i=1`
- better use 1-based indexing, because otherwise `b.getSubBasis(0)` would return `b.getSubBasis{1}` ? -> too confusing

**Comment by jgillis** [comment]
To avoid crashes; there are two solutions:
 * work with assertions `spline_assert(index>=0 && index<allSubBasis.size())`;
 * Work with `at()` instead of `[]` on std::vector

**Comment by ErikLambr** [comment]
Since we have to go through SWIG, I would go for the `spline_assert`

**Comment by jgillis** [comment]
The assertions are now present in Function, but not in TensorBasis.
