### ISSUE TITLE
From Basis back to SubBasis [Matlab+Windows]

### ISSUE THREAD

**Issue by gpipelee** [meco-group/cpp_splines#38]
```
degree = 3;
m = SubMonomialBasis(degree);
sbv = SubBasisVector();
sbv.append(m);
sbv.append(m);
b = Basis.Basis(sbv);
```

`b.getSubBasis{1}` returns a SubMonomialBasis, but `b.getSubBasis{1}.getDegree` yields an error:

"Error using subsref. 
No appropriate method, property, or field 'getDegree' for class 'Basis.SubBasis'."

**Comment by jgillis** [comment]
What if you assign `b.getSubBasis{1}` to a variable first?

**Comment by gpipelee** [comment]
Doesn't make a difference.

```
c = b.getSubBasis{1}
c.getDegree
```
returns the same error, although as far as I can tell, ```c``` is a SubMonomialBasis

**Comment by jgillis** [comment]
Obsolete
