### ISSUE TITLE
Error using Basis.getSize [Matlab+Windows]

### ISSUE THREAD

**Issue by gpipelee** [meco-group/cpp_splines#40]
```
m = SubMonomialBasis(degree);
sbv = SubBasisVector();
sbv.append(m);
sbv.append(m);
b = Basis.Basis(sbv);
b.getSize 
```

"Error using BasisMEX: Requested 1x18446744071694492455 (17179869169.0GB) array exceeds maximum array size preference. Creation of arrays greater than this limit may take a long time and cause MATLAB to become unresponsive. See array size limit or preference panel for more information."

**Comment by ErikLambr** [comment]
solved
