### ISSUE TITLE
Error using Basis.getDimension [Matlab+Windows]

### ISSUE THREAD

**Issue by gpipelee** [meco-group/cpp_splines#41]
```
m = SubMonomialBasis(degree);
sbv = SubBasisVector();
sbv.append(m);
sbv.append(m);
b = Basis.Basis(sbv);
b.getDimension
```

returns `118395104` 
what is the meaning of this number???

**Comment by ErikLambr** [comment]
is it the return of 
`b.getDimension`
or
`b.getDimension()`

**Comment by gpipelee** [comment]
both commands return the same value

**Comment by jgillis** [comment]
This was basically an unimplemented method; with a random piece of memory being interpreted as integer. Seems to have been fixed
