### ISSUE TITLE
Matlab crashes [Matlab+Windows]

### ISSUE THREAD

**Issue by gpipelee** [meco-group/cpp_splines#43]
I guess every time a function is called that is not yet filled in properly, e.g. 

```
m = SubMonomialBasis(degree);
sbv = SubBasisVector();
sbv.append(m);
sbv.append(m);
b = Basis.Basis(sbv);
```
- `b.castBSpline` causes a Matlab crash
- `b.getSubArgument(i)` causes a Matlab crash for every `i`
- ...

**Comment by jgillis** [comment]
Caused by missing return statements. Since compiler warnings have been added; this should be fixed.
