### ISSUE TITLE
What is the use of Basis.castBSpline?

### ISSUE THREAD

**Issue by gpipelee** [meco-group/cpp_splines#44]
- does not make sense for all bases !!
- from the help it seems this can be called without input argument !?

**Comment by ErikLambr** [comment]
Noting jet.

**Comment by gpipelee** [comment]
My point being that I cannot imagine it ever to make sense at the level of ```Basis```...

**Comment by ErikLambr** [comment]
dropt  in 9b6ffb9989a5725513ce743bf55a71564cfec047
