### ISSUE TITLE
Concatenation of Basis elements

### ISSUE THREAD

**Issue by gpipelee** [meco-group/cpp_splines#46]
In Matlab, something like `[basis1, basis2]` should in my opinion make sense.

At this point, it is not yet working properly:

```
degree = 3;
m = SubMonomialBasis(degree);
sbv = SubBasisVector();
sbv.append(m);
sbv.append(m);
b1 = Basis.Basis(sbv);
b2 = Basis.Basis(sbv);
b3 = MonomialBasis(degree);
```
- `[b1,b2]` and `[b1,b3]` return a single Basis
- `[b3,b1]` returns an error because `b1` cannot be converted to a MonomialBasis

**Comment by jgillis** [comment]
Absolutely, this is a SWIG issue

**Comment by jgillis** [comment]
A question maybe if we want `{b1,b2}`, `[b1,b2]`.

**Comment by jgillis** [comment]
We go for `{}` and `varargin`
