### ISSUE TITLE
more convenient way to define univariate function

### ISSUE THREAD

**Issue by rubenvanparys** [meco-group/cpp_splines#52]
Is there the possibility to leave out eg the creation of tensor step in the univariate case?

**Comment by ErikLambr** [comment]
Some like the constructors added in de5cf9f971844b8bbe9cd204124f677bbe121fa7.  
https://github.com/meco-group/cpp_splines/blob/operation_multyvariate/tests/test_function_Function_operations.py#L35
shows the construction of $x**2$

**Comment by rubenvanparys** [comment]
Does there exist a similar definition for splines?
