### ISSUE TITLE
 Autocast DM as scalar / matrix / tensor ...

### ISSUE THREAD

**Issue by gpipelee** [meco-group/cpp_splines#67]
- Autocast output argument of a ```Function``` / ```Basis``` evaluation as a scalar / matrix / tensor ...
- Autocast output argument of ```Coefficient.getData``` as scalar / matrix / tensor ...

**Comment by jgillis** [comment]
For dense numeric Tensors, we can easily map to numpy/matlab tensors.

Problematic case:
 - sparse Tensors
 - symbolic Tensor

**Comment by jgillis** [comment]
Input/output typemaps for matlab tensor/nd numpy arrays fully implemented and tested.

For the remaining problematic case, create a new ticket when the need arises.
