### ISSUE TITLE
dropbox :  develop

### ISSUE THREAD

**Issue by ErikLambr** [meco-group/cpp_splines#81]
Ik heb 
```
echo $MECO_BINARIES_OVERRIDE_CPP_SPLINES                    
/home/erik/Documents/cpp_spline/build/tests/../swig
```
Alles compileerd maar SWIG zoek toch nog in de dropbox 
```
[ 91%] Swig source
:1: Error: Unable to find 'swig.swg'
:3: Error: Unable to find 'python.swg'
/home/erik/Documents/cpp_spline/swig/Basis.i:47: Error: Unable to find 'exception.i'
/home/erik/Documents/cpp_spline/swig/Basis.i:72: Error: Unable to find 'std_vector.i'
/home/erik/Documents/cpp_spline/swig/Basis.i:75: Error: Unable to find 'exception.i'
/home/erik/Dropbox/meco_binaries_debian/python27/casadi/3.1.0/include/casadi/casadi.i:300: Error: Unable to find 'stl.i'
/home/erik/Dropbox/meco_binaries_debian/python27/casadi/3.1.0/include/casadi/casadi.i:309: Error: Unable to find 'exception.i'
```

**Comment by jgillis** [comment]
You must have SWIG_LIB set (e.g. by running env.sh )

Looks unavoidable. The only way to obtain custom SWIG library path (including language-priorities) is SWIG_LIB env variable (per http://www.swig.org/Doc3.0/Library.html). Cmake's UseSWIG.cmake does not provide the possibility for setting environemntal variable for the swig process. Also, generic cmake `set(ENV{...} ...))` does not propagate to subprocess.
